/** @type {import('tailwindcss').Config} */
module.exports = {
  purge: {
    enabled: true,
    content: ["./**/*.liquid"],
  },

  theme: {
    extend: {
      colors: {
        givry: "#F8E4C3",
        "ecru-white": "#F9F7F0",
        woodsmoke: "#131818",
        linen: "#FBF1E7",
        "linen-dark": "#F9E1DE",
        "burnt-sienna": "#EB7462",
        "cape-palliser": "#9E6D44",
        "quarter-spanish-white": "#F7EEDF",
        "bridal-heath": "#FFF8F1",
        "de-york": "#8BC292",
        "white-lilac": "#E7E3F4",
        merino: "#FAF7F1",
        almond: "#F0E2CC",
        supernova: "#FFC80B",
        alto: "#D9D9D9",
        "supernova-2": "#FFC808",
        "grain-brown": "#DFC6AC",
        surf: "#B9DABD",
        "mine-shaft": "#333333",
        "bull-shot": "#884D1C",
        cameo: "#D5B89F",
        "flame-pea": "#DE5844",
        "fruit-salad": "#53A35D",
        "blue-marguerite": "#8573C6",
        tuna: "#313133",
        soapstone: "#FFFBF8",
        "silver-chalice": "#A0A0A0",
        "dove-gray": "#6E6E6E",
        mercury: "#E9E9E9",
      },
      fontFamily: {
        "AnekLatin-Regular": ["AnekLatin-Regular", "sans-serif"],
        "AnekLatin-Medium": ["AnekLatin-Medium", "sans-serif"],
        "AnekLatin-SemiBold": ["AnekLatin-SemiBold", "sans-serif"],
        "AnekLatin-Bold": ["AnekLatin-Bold", "sans-serif"],
        "AnekDevanagari-Regular": ["AnekDevanagari-Regular", "sans-serif"],
        "AnekDevanagari-Medium": ["AnekDevanagari-Medium", "sans-serif"],
        "AnekDevanagari-SemiBold": ["AnekDevanagari-SemiBold", "sans-serif"],
        "AnekDevanagari-Bold": ["AnekDevanagari-Bold", "sans-serif"],
        "AnekDevanagari-ExtraBold": ["AnekDevanagari-ExtraBold", "sans-serif"],
      },
    },
  },
  plugins: [],
}
